"""add is_active and created_at to user

Revision ID: 1c4ca54554fd
Revises: 20260412_0001
Create Date: 2026-04-13 19:20:24.255060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4ca54554fd'
down_revision: Union[str, Sequence[str], None] = '20260412_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
